# Compile & Linking 
CC=g++
LD=g++
AR=ar -r
CFLAGS=-g -Wall -O3
#CFLAGS=-g -Wall -O0
LDFLAGS=
INC=/usr/include/GL /usr/include/freetype2 $(HG_ROOT)/inc
#INC_PATH=$(addprefix -I,$(INC))
INC_PATH=-I/usr/include/GL -I/usr/include/freetype2 -I$(HG_ROOT)/inc
LIBS=-lGL -lGLU -lGLEW -lSDL -lfreetype
LIB_PATH=

MAKE=make
RM=rm -f
CP=cp

